/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_dialog_sens (void);
GtkWidget* create_dialog_zona (void);
GtkWidget* create_dialog_opzioni (void);
GtkWidget* create_dialog_tlc (void);
GtkWidget* create_versione (void);
GtkWidget* create_dialog_att (void);
GtkWidget* create_dialog_evento (void);
GtkWidget* create_dialog_segreto (void);
GtkWidget* create_dialog_generico (void);
