/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *handlebox2;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *cancella1;
  GtkWidget *image28;
  GtkWidget *separatore4;
  GtkWidget *esci1;
  GtkWidget *comandi1;
  GtkWidget *comandi1_menu;
  GtkWidget *sensori1;
  GtkWidget *sensori1_menu;
  GtkWidget *in_servizio1;
  GtkWidget *fuori_servizio1;
  GtkWidget *separatore1;
  GtkWidget *accetta_allarme1;
  GtkWidget *accetta_manomissione1;
  GtkWidget *accetta_guasto1;
  GtkWidget *accettazione_totale1;
  GtkWidget *separatore2;
  GtkWidget *refresh1;
  GtkWidget *attuatori1;
  GtkWidget *attuatori1_menu;
  GtkWidget *in_servizio2;
  GtkWidget *fuori_servizio2;
  GtkWidget *on_attuatore1;
  GtkWidget *on_attuatore_lampeggiante1;
  GtkWidget *off_attuatore1;
  GtkWidget *separatore3;
  GtkWidget *refresh2;
  GtkWidget *zone1;
  GtkWidget *zone1_menu;
  GtkWidget *attiva1;
  GtkWidget *attiva_con_allarme1;
  GtkWidget *attiva_con_fuori_servizio1;
  GtkWidget *disattiva1;
  GtkWidget *radio1;
  GtkWidget *radio1_menu;
  GtkWidget *inizio_manutenzione1;
  GtkWidget *fine_manutenzione1;
  GtkWidget *telecomando1;
  GtkWidget *evento1;
  GtkWidget *segreto1;
  GtkWidget *generico1;
  GtkWidget *lara1;
  GtkWidget *sequenza1;
  GtkWidget *liste1;
  GtkWidget *liste1_menu;
  GtkWidget *sensori2;
  GtkWidget *attuatori2;
  GtkWidget *zone2;
  GtkWidget *sensori3;
  GtkWidget *attuatori3;
  GtkWidget *memoria_utente2;
  GtkWidget *giorni_festivi1;
  GtkWidget *periferiche1;
  GtkWidget *fasce_orarie1;
  GtkWidget *associazione_zone_sensori1;
  GtkWidget *memoria_utente1;
  GtkWidget *allineamento1;
  GtkWidget *opzioni1;
  GtkWidget *opzioni1_menu;
  GtkWidget *opzioni2;
  GtkWidget *image29;
  GtkWidget *separatore5;
  GtkWidget *versione1;
  GtkWidget *image30;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *add_sens;
  GtkWidget *del_sens;
  GtkWidget *add_zona;
  GtkWidget *del_zona;
  GtkWidget *telecomando;
  GtkWidget *orologio;
  GtkWidget *testbtn;
  GtkWidget *avviatest;
  GtkWidget *toolitem1;
  GtkWidget *vseparator4;
  GtkWidget *clear;
  GtkWidget *opzioni;
  GtkWidget *button1;
  GtkWidget *scrolledwindow1;
  GtkWidget *eventi;
  GtkWidget *hbox1;
  GtkWidget *attivo;
  GtkWidget *connetti;
  GtkWidget *centrale;
  GtkWidget *label2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("ComLinux"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 700, 400);
  window1_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), menubar1);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  cancella1 = gtk_image_menu_item_new_with_mnemonic (_("Cancella"));
  gtk_widget_show (cancella1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), cancella1);

  image28 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image28);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (cancella1), image28);

  separatore4 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatore4);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatore4);
  gtk_widget_set_sensitive (separatore4, FALSE);

  esci1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (esci1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), esci1);

  comandi1 = gtk_menu_item_new_with_mnemonic (_("_Comandi"));
  gtk_widget_show (comandi1);
  gtk_container_add (GTK_CONTAINER (menubar1), comandi1);

  comandi1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (comandi1), comandi1_menu);

  sensori1 = gtk_menu_item_new_with_mnemonic (_("Sensori"));
  gtk_widget_show (sensori1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), sensori1);

  sensori1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (sensori1), sensori1_menu);

  in_servizio1 = gtk_menu_item_new_with_mnemonic (_("In servizio"));
  gtk_widget_show (in_servizio1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), in_servizio1);

  fuori_servizio1 = gtk_menu_item_new_with_mnemonic (_("Fuori servizio"));
  gtk_widget_show (fuori_servizio1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), fuori_servizio1);

  separatore1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatore1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), separatore1);
  gtk_widget_set_sensitive (separatore1, FALSE);

  accetta_allarme1 = gtk_menu_item_new_with_mnemonic (_("Accetta allarme"));
  gtk_widget_show (accetta_allarme1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), accetta_allarme1);

  accetta_manomissione1 = gtk_menu_item_new_with_mnemonic (_("Accetta manomissione"));
  gtk_widget_show (accetta_manomissione1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), accetta_manomissione1);

  accetta_guasto1 = gtk_menu_item_new_with_mnemonic (_("Accetta guasto"));
  gtk_widget_show (accetta_guasto1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), accetta_guasto1);

  accettazione_totale1 = gtk_menu_item_new_with_mnemonic (_("Accettazione totale"));
  gtk_widget_show (accettazione_totale1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), accettazione_totale1);

  separatore2 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatore2);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), separatore2);
  gtk_widget_set_sensitive (separatore2, FALSE);

  refresh1 = gtk_menu_item_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresh1);
  gtk_container_add (GTK_CONTAINER (sensori1_menu), refresh1);

  attuatori1 = gtk_menu_item_new_with_mnemonic (_("Attuatori"));
  gtk_widget_show (attuatori1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), attuatori1);

  attuatori1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (attuatori1), attuatori1_menu);

  in_servizio2 = gtk_menu_item_new_with_mnemonic (_("In servizio"));
  gtk_widget_show (in_servizio2);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), in_servizio2);

  fuori_servizio2 = gtk_menu_item_new_with_mnemonic (_("Fuori servizio"));
  gtk_widget_show (fuori_servizio2);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), fuori_servizio2);

  on_attuatore1 = gtk_menu_item_new_with_mnemonic (_("On attuatore"));
  gtk_widget_show (on_attuatore1);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), on_attuatore1);

  on_attuatore_lampeggiante1 = gtk_menu_item_new_with_mnemonic (_("On attuatore lamp."));
  gtk_widget_show (on_attuatore_lampeggiante1);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), on_attuatore_lampeggiante1);

  off_attuatore1 = gtk_menu_item_new_with_mnemonic (_("Off attuatore"));
  gtk_widget_show (off_attuatore1);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), off_attuatore1);

  separatore3 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatore3);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), separatore3);
  gtk_widget_set_sensitive (separatore3, FALSE);

  refresh2 = gtk_menu_item_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresh2);
  gtk_container_add (GTK_CONTAINER (attuatori1_menu), refresh2);

  zone1 = gtk_menu_item_new_with_mnemonic (_("Zone"));
  gtk_widget_show (zone1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), zone1);

  zone1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (zone1), zone1_menu);

  attiva1 = gtk_menu_item_new_with_mnemonic (_("Attiva"));
  gtk_widget_show (attiva1);
  gtk_container_add (GTK_CONTAINER (zone1_menu), attiva1);

  attiva_con_allarme1 = gtk_menu_item_new_with_mnemonic (_("Attiva con allarme"));
  gtk_widget_show (attiva_con_allarme1);
  gtk_container_add (GTK_CONTAINER (zone1_menu), attiva_con_allarme1);

  attiva_con_fuori_servizio1 = gtk_menu_item_new_with_mnemonic (_("Attiva con fuori servizio"));
  gtk_widget_show (attiva_con_fuori_servizio1);
  gtk_container_add (GTK_CONTAINER (zone1_menu), attiva_con_fuori_servizio1);

  disattiva1 = gtk_menu_item_new_with_mnemonic (_("Disattiva"));
  gtk_widget_show (disattiva1);
  gtk_container_add (GTK_CONTAINER (zone1_menu), disattiva1);

  radio1 = gtk_menu_item_new_with_mnemonic (_("Radio"));
  gtk_widget_show (radio1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), radio1);

  radio1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (radio1), radio1_menu);

  inizio_manutenzione1 = gtk_menu_item_new_with_mnemonic (_("Inizio manutenzione"));
  gtk_widget_show (inizio_manutenzione1);
  gtk_container_add (GTK_CONTAINER (radio1_menu), inizio_manutenzione1);

  fine_manutenzione1 = gtk_menu_item_new_with_mnemonic (_("Fine manutenzione"));
  gtk_widget_show (fine_manutenzione1);
  gtk_container_add (GTK_CONTAINER (radio1_menu), fine_manutenzione1);

  telecomando1 = gtk_menu_item_new_with_mnemonic (_("Telecomando"));
  gtk_widget_show (telecomando1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), telecomando1);

  evento1 = gtk_menu_item_new_with_mnemonic (_("Evento"));
  gtk_widget_show (evento1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), evento1);

  segreto1 = gtk_menu_item_new_with_mnemonic (_("Segreto"));
  gtk_widget_show (segreto1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), segreto1);

  generico1 = gtk_menu_item_new_with_mnemonic (_("Generico"));
  gtk_widget_show (generico1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), generico1);

  lara1 = gtk_menu_item_new_with_mnemonic (_("Lara"));
  gtk_widget_show (lara1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), lara1);

  sequenza1 = gtk_menu_item_new_with_mnemonic (_("Da file..."));
  gtk_widget_show (sequenza1);
  gtk_container_add (GTK_CONTAINER (comandi1_menu), sequenza1);

  liste1 = gtk_menu_item_new_with_mnemonic (_("_Liste"));
  gtk_widget_show (liste1);
  gtk_container_add (GTK_CONTAINER (menubar1), liste1);

  liste1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (liste1), liste1_menu);

  sensori2 = gtk_menu_item_new_with_mnemonic (_("Sensori fuori servizio"));
  gtk_widget_show (sensori2);
  gtk_container_add (GTK_CONTAINER (liste1_menu), sensori2);

  attuatori2 = gtk_menu_item_new_with_mnemonic (_("Attuatori fuori servizio"));
  gtk_widget_show (attuatori2);
  gtk_container_add (GTK_CONTAINER (liste1_menu), attuatori2);

  zone2 = gtk_menu_item_new_with_mnemonic (_("Zone"));
  gtk_widget_show (zone2);
  gtk_container_add (GTK_CONTAINER (liste1_menu), zone2);

  sensori3 = gtk_menu_item_new_with_mnemonic (_("Sensori"));
  gtk_widget_show (sensori3);
  gtk_container_add (GTK_CONTAINER (liste1_menu), sensori3);

  attuatori3 = gtk_menu_item_new_with_mnemonic (_("Attuatori"));
  gtk_widget_show (attuatori3);
  gtk_container_add (GTK_CONTAINER (liste1_menu), attuatori3);

  memoria_utente2 = gtk_menu_item_new_with_mnemonic (_("Memoria utente"));
  gtk_widget_show (memoria_utente2);
  gtk_container_add (GTK_CONTAINER (liste1_menu), memoria_utente2);

  giorni_festivi1 = gtk_menu_item_new_with_mnemonic (_("Giorni festivi"));
  gtk_widget_show (giorni_festivi1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), giorni_festivi1);

  periferiche1 = gtk_menu_item_new_with_mnemonic (_("Periferiche"));
  gtk_widget_show (periferiche1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), periferiche1);

  fasce_orarie1 = gtk_menu_item_new_with_mnemonic (_("Fasce orarie"));
  gtk_widget_show (fasce_orarie1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), fasce_orarie1);

  associazione_zone_sensori1 = gtk_menu_item_new_with_mnemonic (_("Associazione zone/sensori"));
  gtk_widget_show (associazione_zone_sensori1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), associazione_zone_sensori1);

  memoria_utente1 = gtk_menu_item_new_with_mnemonic (_("Codici di controllo"));
  gtk_widget_show (memoria_utente1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), memoria_utente1);

  allineamento1 = gtk_menu_item_new_with_mnemonic (_("Allineamento"));
  gtk_widget_show (allineamento1);
  gtk_container_add (GTK_CONTAINER (liste1_menu), allineamento1);

  opzioni1 = gtk_menu_item_new_with_mnemonic (_("Opzioni"));
  gtk_widget_show (opzioni1);
  gtk_container_add (GTK_CONTAINER (menubar1), opzioni1);

  opzioni1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (opzioni1), opzioni1_menu);

  opzioni2 = gtk_image_menu_item_new_with_mnemonic (_("Opzioni"));
  gtk_widget_show (opzioni2);
  gtk_container_add (GTK_CONTAINER (opzioni1_menu), opzioni2);

  image29 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image29);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (opzioni2), image29);

  separatore5 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatore5);
  gtk_container_add (GTK_CONTAINER (opzioni1_menu), separatore5);
  gtk_widget_set_sensitive (separatore5, FALSE);

  versione1 = gtk_image_menu_item_new_with_mnemonic (_("Versione"));
  gtk_widget_show (versione1);
  gtk_container_add (GTK_CONTAINER (opzioni1_menu), versione1);

  image30 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image30);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (versione1), image30);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, TRUE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_sens = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Sensore"));
  gtk_widget_show (add_sens);
  gtk_container_add (GTK_CONTAINER (toolbar1), add_sens);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  del_sens = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Sensore"));
  gtk_widget_show (del_sens);
  gtk_container_add (GTK_CONTAINER (toolbar1), del_sens);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_zona = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Zona"));
  gtk_widget_show (add_zona);
  gtk_container_add (GTK_CONTAINER (toolbar1), add_zona);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  del_zona = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Zona"));
  gtk_widget_show (del_zona);
  gtk_container_add (GTK_CONTAINER (toolbar1), del_zona);

  tmp_image = gtk_image_new_from_stock ("gtk-jump-to", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  telecomando = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Telec"));
  gtk_widget_show (telecomando);
  gtk_container_add (GTK_CONTAINER (toolbar1), telecomando);

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  orologio = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Orologio"));
  gtk_widget_show (orologio);
  gtk_container_add (GTK_CONTAINER (toolbar1), orologio);

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  testbtn = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Test"));
  gtk_widget_show (testbtn);
  gtk_container_add (GTK_CONTAINER (toolbar1), testbtn);

#ifdef AVVIATEST
  tmp_image = gtk_image_new_from_stock ("gtk-yes", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  avviatest = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Test"));
  gtk_widget_show (avviatest);
  gtk_container_add (GTK_CONTAINER (toolbar1), avviatest);
#endif

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_container_add (GTK_CONTAINER (toolitem1), vseparator4);

  tmp_image = gtk_image_new_from_stock ("gtk-delete", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  clear = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Cancella"));
  gtk_widget_show (clear);
  gtk_container_add (GTK_CONTAINER (toolbar1), clear);

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  opzioni = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Opzioni"));
  gtk_widget_show (opzioni);
  gtk_container_add (GTK_CONTAINER (toolbar1), opzioni);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button1 = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Esci"));
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (toolbar1), button1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);

  eventi = gtk_text_view_new ();
  gtk_widget_show (eventi);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), eventi);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (eventi), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (eventi), FALSE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  attivo = gtk_drawing_area_new ();
  gtk_widget_show (attivo);
  gtk_box_pack_start (GTK_BOX (hbox1), attivo, FALSE, FALSE, 2);
  gtk_widget_set_size_request (attivo, 10, -1);

  connetti = gtk_toggle_button_new_with_mnemonic (_("Connetti"));
  gtk_widget_show (connetti);
  gtk_box_pack_start (GTK_BOX (hbox1), connetti, FALSE, FALSE, 0);

  centrale = gtk_label_new ("");
  gtk_widget_show (centrale);
  gtk_box_pack_start (GTK_BOX (hbox1), centrale, TRUE, TRUE, 5);
  gtk_label_set_justify (GTK_LABEL (centrale), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (centrale), 1, 0.5);

  label2 = gtk_label_new ("");
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) cancella1, "activate",
                    G_CALLBACK (on_cancella1_activate),
                    NULL);
  g_signal_connect ((gpointer) esci1, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) comandi1, "activate",
                    G_CALLBACK (on_comandi1_activate),
                    NULL);
  g_signal_connect ((gpointer) sensori1, "activate",
                    G_CALLBACK (on_sensori1_activate),
                    NULL);
  g_signal_connect ((gpointer) in_servizio1, "activate",
                    G_CALLBACK (on_in_servizio1_activate),
                    NULL);
  g_signal_connect ((gpointer) fuori_servizio1, "activate",
                    G_CALLBACK (on_fuori_servizio1_activate),
                    NULL);
  g_signal_connect ((gpointer) accetta_allarme1, "activate",
                    G_CALLBACK (on_accetta_allarme1_activate),
                    NULL);
  g_signal_connect ((gpointer) accetta_manomissione1, "activate",
                    G_CALLBACK (on_accetta_manomissione1_activate),
                    NULL);
  g_signal_connect ((gpointer) accetta_guasto1, "activate",
                    G_CALLBACK (on_accetta_guasto1_activate),
                    NULL);
  g_signal_connect ((gpointer) accettazione_totale1, "activate",
                    G_CALLBACK (on_accettazione_totale1_activate),
                    NULL);
  g_signal_connect ((gpointer) refresh1, "activate",
                    G_CALLBACK (on_refresh1_activate),
                    NULL);
  g_signal_connect ((gpointer) attuatori1, "activate",
                    G_CALLBACK (on_attuatori1_activate),
                    NULL);
  g_signal_connect ((gpointer) in_servizio2, "activate",
                    G_CALLBACK (on_in_servizio2_activate),
                    NULL);
  g_signal_connect ((gpointer) fuori_servizio2, "activate",
                    G_CALLBACK (on_fuori_servizio2_activate),
                    NULL);
  g_signal_connect ((gpointer) on_attuatore1, "activate",
                    G_CALLBACK (on_on_attuatore1_activate),
                    NULL);
  g_signal_connect ((gpointer) on_attuatore_lampeggiante1, "activate",
                    G_CALLBACK (on_on_attuatore_lampeggiante1_activate),
                    NULL);
  g_signal_connect ((gpointer) off_attuatore1, "activate",
                    G_CALLBACK (on_off_attuatore1_activate),
                    NULL);
  g_signal_connect ((gpointer) refresh2, "activate",
                    G_CALLBACK (on_refresh2_activate),
                    NULL);
  g_signal_connect ((gpointer) zone1, "activate",
                    G_CALLBACK (on_zone1_activate),
                    NULL);
  g_signal_connect ((gpointer) attiva1, "activate",
                    G_CALLBACK (on_attiva1_activate),
                    NULL);
  g_signal_connect ((gpointer) attiva_con_allarme1, "activate",
                    G_CALLBACK (on_attiva_con_allarme1_activate),
                    NULL);
  g_signal_connect ((gpointer) attiva_con_fuori_servizio1, "activate",
                    G_CALLBACK (on_attiva_con_fuori_servizio1_activate),
                    NULL);
  g_signal_connect ((gpointer) disattiva1, "activate",
                    G_CALLBACK (on_disattiva1_activate),
                    NULL);
  g_signal_connect ((gpointer) radio1, "activate",
                    G_CALLBACK (on_radio1_activate),
                    NULL);
  g_signal_connect ((gpointer) inizio_manutenzione1, "activate",
                    G_CALLBACK (on_inizio_manutenzione1_activate),
                    NULL);
  g_signal_connect ((gpointer) fine_manutenzione1, "activate",
                    G_CALLBACK (on_fine_manutenzione1_activate),
                    NULL);
  g_signal_connect ((gpointer) telecomando1, "activate",
                    G_CALLBACK (on_telecomando1_activate),
                    NULL);
  g_signal_connect ((gpointer) evento1, "activate",
                    G_CALLBACK (on_evento1_activate),
                    NULL);
  g_signal_connect ((gpointer) segreto1, "activate",
                    G_CALLBACK (on_segreto1_activate),
                    NULL);
  g_signal_connect ((gpointer) generico1, "activate",
                    G_CALLBACK (on_generico1_activate),
                    NULL);
  g_signal_connect ((gpointer) lara1, "activate",
                    G_CALLBACK (on_lara1_activate),
                    NULL);
  g_signal_connect ((gpointer) sequenza1, "activate",
                    G_CALLBACK (on_sequenza1_activate),
                    NULL);
  g_signal_connect ((gpointer) liste1, "activate",
                    G_CALLBACK (on_liste1_activate),
                    NULL);
  g_signal_connect ((gpointer) sensori2, "activate",
                    G_CALLBACK (on_sensori2_activate),
                    NULL);
  g_signal_connect ((gpointer) attuatori2, "activate",
                    G_CALLBACK (on_attuatori2_activate),
                    NULL);
  g_signal_connect ((gpointer) zone2, "activate",
                    G_CALLBACK (on_zone2_activate),
                    NULL);
  g_signal_connect ((gpointer) sensori3, "activate",
                    G_CALLBACK (on_sensori3_activate),
                    NULL);
  g_signal_connect ((gpointer) attuatori3, "activate",
                    G_CALLBACK (on_attuatori3_activate),
                    NULL);
  g_signal_connect ((gpointer) memoria_utente2, "activate",
                    G_CALLBACK (on_memoria_utente2_activate),
                    NULL);
  g_signal_connect ((gpointer) giorni_festivi1, "activate",
                    G_CALLBACK (on_giorni_festivi1_activate),
                    NULL);
  g_signal_connect ((gpointer) periferiche1, "activate",
                    G_CALLBACK (on_periferiche1_activate),
                    NULL);
  g_signal_connect ((gpointer) fasce_orarie1, "activate",
                    G_CALLBACK (on_fasce_orarie1_activate),
                    NULL);
  g_signal_connect ((gpointer) associazione_zone_sensori1, "activate",
                    G_CALLBACK (on_associazione_zone_sensori1_activate),
                    NULL);
  g_signal_connect ((gpointer) memoria_utente1, "activate",
                    G_CALLBACK (on_memoria_utente1_activate),
                    NULL);
  g_signal_connect ((gpointer) allineamento1, "activate",
                    G_CALLBACK (on_allineamento1_activate),
                    NULL);
  g_signal_connect ((gpointer) opzioni1, "activate",
                    G_CALLBACK (on_opzioni1_activate),
                    NULL);
  g_signal_connect ((gpointer) opzioni2, "activate",
                    G_CALLBACK (on_opzioni2_activate),
                    NULL);
  g_signal_connect ((gpointer) versione1, "activate",
                    G_CALLBACK (on_versione1_activate),
                    NULL);
  g_signal_connect ((gpointer) add_sens, "clicked",
                    G_CALLBACK (on_add_sens_clicked),
                    NULL);
  g_signal_connect ((gpointer) del_sens, "clicked",
                    G_CALLBACK (on_del_sens_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_zona, "clicked",
                    G_CALLBACK (on_add_zona_clicked),
                    NULL);
  g_signal_connect ((gpointer) del_zona, "clicked",
                    G_CALLBACK (on_del_zona_clicked),
                    NULL);
  g_signal_connect ((gpointer) telecomando, "clicked",
                    G_CALLBACK (on_telecomando_clicked),
                    NULL);
  g_signal_connect ((gpointer) orologio, "clicked",
                    G_CALLBACK (on_orologio_clicked),
                    NULL);
  g_signal_connect ((gpointer) testbtn, "clicked",
                    G_CALLBACK (on_testbtn_clicked),
                    NULL);
#ifdef AVVIATEST
  g_signal_connect ((gpointer) avviatest, "clicked",
                    G_CALLBACK (on_avviatest_clicked),
                    NULL);
#endif
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) opzioni, "clicked",
                    G_CALLBACK (on_opzioni_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) eventi, "realize",
                    G_CALLBACK (on_eventi_realize),
                    NULL);
  g_signal_connect ((gpointer) eventi, "populate_popup",
                    G_CALLBACK (on_eventi_populate_popup),
                    NULL);
  g_signal_connect ((gpointer) attivo, "expose_event",
                    G_CALLBACK (on_attivo_expose_event),
                    NULL);
  g_signal_connect ((gpointer) connetti, "toggled",
                    G_CALLBACK (on_connetti_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (window1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window1, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window1, cancella1, "cancella1");
  GLADE_HOOKUP_OBJECT (window1, image28, "image28");
  GLADE_HOOKUP_OBJECT (window1, separatore4, "separatore4");
  GLADE_HOOKUP_OBJECT (window1, esci1, "esci1");
  GLADE_HOOKUP_OBJECT (window1, comandi1, "comandi1");
  GLADE_HOOKUP_OBJECT (window1, comandi1_menu, "comandi1_menu");
  GLADE_HOOKUP_OBJECT (window1, sensori1, "sensori1");
  GLADE_HOOKUP_OBJECT (window1, sensori1_menu, "sensori1_menu");
  GLADE_HOOKUP_OBJECT (window1, in_servizio1, "in_servizio1");
  GLADE_HOOKUP_OBJECT (window1, fuori_servizio1, "fuori_servizio1");
  GLADE_HOOKUP_OBJECT (window1, separatore1, "separatore1");
  GLADE_HOOKUP_OBJECT (window1, accetta_allarme1, "accetta_allarme1");
  GLADE_HOOKUP_OBJECT (window1, accetta_manomissione1, "accetta_manomissione1");
  GLADE_HOOKUP_OBJECT (window1, accetta_guasto1, "accetta_guasto1");
  GLADE_HOOKUP_OBJECT (window1, accettazione_totale1, "accettazione_totale1");
  GLADE_HOOKUP_OBJECT (window1, separatore2, "separatore2");
  GLADE_HOOKUP_OBJECT (window1, refresh1, "refresh1");
  GLADE_HOOKUP_OBJECT (window1, attuatori1, "attuatori1");
  GLADE_HOOKUP_OBJECT (window1, attuatori1_menu, "attuatori1_menu");
  GLADE_HOOKUP_OBJECT (window1, in_servizio2, "in_servizio2");
  GLADE_HOOKUP_OBJECT (window1, fuori_servizio2, "fuori_servizio2");
  GLADE_HOOKUP_OBJECT (window1, on_attuatore1, "on_attuatore1");
  GLADE_HOOKUP_OBJECT (window1, on_attuatore_lampeggiante1, "on_attuatore_lampeggiante1");
  GLADE_HOOKUP_OBJECT (window1, off_attuatore1, "off_attuatore1");
  GLADE_HOOKUP_OBJECT (window1, separatore3, "separatore3");
  GLADE_HOOKUP_OBJECT (window1, refresh2, "refresh2");
  GLADE_HOOKUP_OBJECT (window1, zone1, "zone1");
  GLADE_HOOKUP_OBJECT (window1, zone1_menu, "zone1_menu");
  GLADE_HOOKUP_OBJECT (window1, attiva1, "attiva1");
  GLADE_HOOKUP_OBJECT (window1, attiva_con_allarme1, "attiva_con_allarme1");
  GLADE_HOOKUP_OBJECT (window1, attiva_con_fuori_servizio1, "attiva_con_fuori_servizio1");
  GLADE_HOOKUP_OBJECT (window1, disattiva1, "disattiva1");
  GLADE_HOOKUP_OBJECT (window1, radio1, "radio1");
  GLADE_HOOKUP_OBJECT (window1, radio1_menu, "radio1_menu");
  GLADE_HOOKUP_OBJECT (window1, inizio_manutenzione1, "inizio_manutenzione1");
  GLADE_HOOKUP_OBJECT (window1, fine_manutenzione1, "fine_manutenzione1");
  GLADE_HOOKUP_OBJECT (window1, telecomando1, "telecomando1");
  GLADE_HOOKUP_OBJECT (window1, evento1, "evento1");
  GLADE_HOOKUP_OBJECT (window1, segreto1, "segreto1");
  GLADE_HOOKUP_OBJECT (window1, generico1, "generico1");
  GLADE_HOOKUP_OBJECT (window1, lara1, "lara1");
  GLADE_HOOKUP_OBJECT (window1, liste1, "liste1");
  GLADE_HOOKUP_OBJECT (window1, liste1_menu, "liste1_menu");
  GLADE_HOOKUP_OBJECT (window1, sensori2, "sensori2");
  GLADE_HOOKUP_OBJECT (window1, attuatori2, "attuatori2");
  GLADE_HOOKUP_OBJECT (window1, zone2, "zone2");
  GLADE_HOOKUP_OBJECT (window1, sensori3, "sensori3");
  GLADE_HOOKUP_OBJECT (window1, attuatori3, "attuatori3");
  GLADE_HOOKUP_OBJECT (window1, memoria_utente2, "memoria_utente2");
  GLADE_HOOKUP_OBJECT (window1, giorni_festivi1, "giorni_festivi1");
  GLADE_HOOKUP_OBJECT (window1, periferiche1, "periferiche1");
  GLADE_HOOKUP_OBJECT (window1, fasce_orarie1, "fasce_orarie1");
  GLADE_HOOKUP_OBJECT (window1, associazione_zone_sensori1, "associazione_zone_sensori1");
  GLADE_HOOKUP_OBJECT (window1, memoria_utente1, "memoria_utente1");
  GLADE_HOOKUP_OBJECT (window1, allineamento1, "allineamento1");
  GLADE_HOOKUP_OBJECT (window1, opzioni1, "opzioni1");
  GLADE_HOOKUP_OBJECT (window1, opzioni1_menu, "opzioni1_menu");
  GLADE_HOOKUP_OBJECT (window1, opzioni2, "opzioni2");
  GLADE_HOOKUP_OBJECT (window1, image29, "image29");
  GLADE_HOOKUP_OBJECT (window1, separatore5, "separatore5");
  GLADE_HOOKUP_OBJECT (window1, versione1, "versione1");
  GLADE_HOOKUP_OBJECT (window1, image30, "image30");
  GLADE_HOOKUP_OBJECT (window1, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, add_sens, "add_sens");
  GLADE_HOOKUP_OBJECT (window1, del_sens, "del_sens");
  GLADE_HOOKUP_OBJECT (window1, add_zona, "add_zona");
  GLADE_HOOKUP_OBJECT (window1, del_zona, "del_zona");
  GLADE_HOOKUP_OBJECT (window1, telecomando, "telecomando");
  GLADE_HOOKUP_OBJECT (window1, orologio, "orologio");
#ifdef AVVIATEST
  GLADE_HOOKUP_OBJECT (window1, avviatest, "avviatest");
#endif
  GLADE_HOOKUP_OBJECT (window1, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (window1, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, opzioni, "opzioni");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, eventi, "eventi");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, attivo, "attivo");
  GLADE_HOOKUP_OBJECT (window1, connetti, "connetti");
  GLADE_HOOKUP_OBJECT (window1, centrale, "centrale");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

GtkWidget*
create_dialog_sens (void)
{
  GtkWidget *dialog_sens;
  GdkPixbuf *dialog_sens_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *entry1;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog_sens = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_sens), _("Sensore"));
  gtk_window_set_modal (GTK_WINDOW (dialog_sens), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_sens), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_sens), TRUE);
  dialog_sens_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (dialog_sens_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_sens), dialog_sens_icon_pixbuf);
      gdk_pixbuf_unref (dialog_sens_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog_sens), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_sens), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_sens)->vbox;
  gtk_widget_show (dialog_vbox1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), entry1, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dialog_sens)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_sens), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_sens), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_sens, dialog_sens, "dialog_sens");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_sens, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_sens, entry1, "entry1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_sens, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_sens, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_sens, okbutton1, "okbutton1");

  return dialog_sens;
}

GtkWidget*
create_dialog_zona (void)
{
  GtkWidget *dialog_zona;
  GdkPixbuf *dialog_zona_icon_pixbuf;
  GtkWidget *dialog_vbox2;
  GtkWidget *hbox2;
  GtkWidget *vbox2;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *entry2;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  dialog_zona = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_zona), _("Zona"));
  gtk_window_set_modal (GTK_WINDOW (dialog_zona), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_zona), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_zona), TRUE);
  dialog_zona_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (dialog_zona_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_zona), dialog_zona_icon_pixbuf);
      gdk_pixbuf_unref (dialog_zona_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog_zona), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_zona), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_zona)->vbox;
  gtk_widget_show (dialog_vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hbox2, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox2, TRUE, TRUE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("semplice"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("insieme"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("totale"));
  gtk_widget_show (radiobutton3);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (hbox2), entry2, TRUE, TRUE, 0);

  dialog_action_area2 = GTK_DIALOG (dialog_zona)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_zona), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_zona), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_zona, dialog_zona, "dialog_zona");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_zona, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_zona, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dialog_zona, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dialog_zona, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (dialog_zona, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (dialog_zona, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (dialog_zona, entry2, "entry2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_zona, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_zona, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog_zona, okbutton2, "okbutton2");

  return dialog_zona;
}

GtkWidget*
create_dialog_opzioni (void)
{
  GtkWidget *dialog_opzioni;
  GdkPixbuf *dialog_opzioni_icon_pixbuf;
  GtkWidget *dialog_vbox3;
  GtkWidget *table1;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *hseparator3;
  GtkWidget *entry_device;
  GtkWidget *entry_ip;
  GtkWidget *entry_port;
  GtkWidget *entry_baud;
  GtkWidget *hseparator4;
  GtkWidget *hseparator5;
  GtkWidget *hseparator6;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *entry_poll;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *label4;
  GtkWidget *label6;
  GtkWidget *label8;
  GtkWidget *opt_lan;
  GSList *opt_lan_group = NULL;
  GtkWidget *opt_ser;
  GtkWidget *opt_udp;
  GtkWidget *vseparator3;
  GtkWidget *label10;
  GtkWidget *entry_ip2;
  GtkWidget *label11;
  GtkWidget *entry_port2;
  GtkWidget *debug;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton_opt;
  GtkWidget *okbutton_opt;

  dialog_opzioni = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_opzioni), _("Opzioni"));
  gtk_window_set_modal (GTK_WINDOW (dialog_opzioni), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_opzioni), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_opzioni), TRUE);
  dialog_opzioni_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (dialog_opzioni_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_opzioni), dialog_opzioni_icon_pixbuf);
      gdk_pixbuf_unref (dialog_opzioni_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog_opzioni), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_opzioni), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_opzioni)->vbox;
  gtk_widget_show (dialog_vbox3);

  table1 = gtk_table_new (5, 6, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), table1, TRUE, TRUE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table1), hseparator1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (table1), hseparator2, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_table_attach (GTK_TABLE (table1), hseparator3, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry_device = gtk_entry_new ();
  gtk_widget_show (entry_device);
  gtk_table_attach (GTK_TABLE (table1), entry_device, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry_device, FALSE);

  entry_ip = gtk_entry_new ();
  gtk_widget_show (entry_ip);
  gtk_table_attach (GTK_TABLE (table1), entry_ip, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_port = gtk_entry_new ();
  gtk_widget_show (entry_port);
  gtk_table_attach (GTK_TABLE (table1), entry_port, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_baud = gtk_entry_new ();
  gtk_widget_show (entry_baud);
  gtk_table_attach (GTK_TABLE (table1), entry_baud, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry_baud, FALSE);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_table_attach (GTK_TABLE (table1), hseparator4, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_table_attach (GTK_TABLE (table1), hseparator5, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_table_attach (GTK_TABLE (table1), hseparator6, 5, 6, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_table_attach (GTK_TABLE (table1), vseparator1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_table_attach (GTK_TABLE (table1), vseparator2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry_poll = gtk_entry_new ();
  gtk_widget_show (entry_poll);
  gtk_table_attach (GTK_TABLE (table1), entry_poll, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("port"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label7 = gtk_label_new (_("baud"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  label4 = gtk_label_new (_("IP"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label6 = gtk_label_new (_("device"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label8 = gtk_label_new (_("Polling:"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  opt_lan = gtk_radio_button_new_with_mnemonic (NULL, _("LAN"));
  gtk_widget_show (opt_lan);
  gtk_table_attach (GTK_TABLE (table1), opt_lan, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (opt_lan), opt_lan_group);
  opt_lan_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (opt_lan));

  opt_ser = gtk_radio_button_new_with_mnemonic (NULL, _("Seriale"));
  gtk_widget_show (opt_ser);
  gtk_table_attach (GTK_TABLE (table1), opt_ser, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (opt_ser), opt_lan_group);
  opt_lan_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (opt_ser));

  opt_udp = gtk_radio_button_new_with_mnemonic (NULL, _("UDP"));
  gtk_widget_show (opt_udp);
  gtk_table_attach (GTK_TABLE (table1), opt_udp, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (opt_udp), opt_lan_group);
  opt_lan_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (opt_udp));

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_table_attach (GTK_TABLE (table1), vseparator3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label10 = gtk_label_new (_("IP"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  entry_ip2 = gtk_entry_new ();
  gtk_widget_show (entry_ip2);
  gtk_table_attach (GTK_TABLE (table1), entry_ip2, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry_ip2, FALSE);

  label11 = gtk_label_new (_("port"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  entry_port2 = gtk_entry_new ();
  gtk_widget_show (entry_port2);
  gtk_table_attach (GTK_TABLE (table1), entry_port2, 5, 6, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (entry_port2, FALSE);

  debug = gtk_check_button_new_with_mnemonic (_("Debug"));
  gtk_widget_show (debug);
  gtk_table_attach (GTK_TABLE (table1), debug, 5, 6, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area3 = GTK_DIALOG (dialog_opzioni)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton_opt = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton_opt);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_opzioni), cancelbutton_opt, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton_opt, GTK_CAN_DEFAULT);

  okbutton_opt = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton_opt);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_opzioni), okbutton_opt, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton_opt, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dialog_opzioni, "show",
                    G_CALLBACK (on_dialog_opzioni_show),
                    NULL);
  g_signal_connect ((gpointer) opt_lan, "toggled",
                    G_CALLBACK (on_opt_lan_toggled),
                    NULL);
  g_signal_connect ((gpointer) opt_ser, "toggled",
                    G_CALLBACK (on_opt_ser_toggled),
                    NULL);
  g_signal_connect ((gpointer) opt_udp, "toggled",
                    G_CALLBACK (on_opt_udp_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_opzioni, dialog_opzioni, "dialog_opzioni");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_opzioni, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, table1, "table1");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_device, "entry_device");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_ip, "entry_ip");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_port, "entry_port");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_baud, "entry_baud");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_poll, "entry_poll");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label5, "label5");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label7, "label7");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label4, "label4");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label6, "label6");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label8, "label8");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, opt_lan, "opt_lan");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, opt_ser, "opt_ser");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, opt_udp, "opt_udp");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label10, "label10");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_ip2, "entry_ip2");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, label11, "label11");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, entry_port2, "entry_port2");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, debug, "debug");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_opzioni, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, cancelbutton_opt, "cancelbutton_opt");
  GLADE_HOOKUP_OBJECT (dialog_opzioni, okbutton_opt, "okbutton_opt");

  return dialog_opzioni;
}

GtkWidget*
create_dialog_tlc (void)
{
  GtkWidget *dialog_tlc;
  GdkPixbuf *dialog_tlc_icon_pixbuf;
  GtkWidget *dialog_vbox4;
  GtkWidget *entry3;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton2;
  GSList *radiobutton_group = NULL;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancelbutton3;
  GtkWidget *okbutton3;

  dialog_tlc = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_tlc), _("Telecomando"));
  gtk_window_set_modal (GTK_WINDOW (dialog_tlc), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_tlc), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_tlc), TRUE);
  dialog_tlc_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (dialog_tlc_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_tlc), dialog_tlc_icon_pixbuf);
      gdk_pixbuf_unref (dialog_tlc_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog_tlc), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_tlc), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_tlc)->vbox;
  gtk_widget_show (dialog_vbox4);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), entry3, FALSE, FALSE, 0);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("3 cifre"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton_group);
  radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("4 cifre"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton_group);
  radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  dialog_action_area4 = GTK_DIALOG (dialog_tlc)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancelbutton3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_tlc), cancelbutton3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton3, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_tlc), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_tlc, dialog_tlc, "dialog_tlc");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_tlc, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_tlc, entry3, "entry3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_tlc, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_tlc, cancelbutton3, "cancelbutton3");
  GLADE_HOOKUP_OBJECT (dialog_tlc, okbutton3, "okbutton3");
  GLADE_HOOKUP_OBJECT (dialog_tlc, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (dialog_tlc, radiobutton2, "radiobutton2");

  return dialog_tlc;
}

GtkWidget*
create_versione (void)
{
  GtkWidget *versione;
  GdkPixbuf *versione_icon_pixbuf;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox3;
  GtkWidget *label9;
  GtkWidget *label_versione;
  GtkWidget *dialog_action_area5;
  GtkWidget *closebutton1;

  versione = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (versione), _("Versione"));
  gtk_window_set_modal (GTK_WINDOW (versione), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (versione), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (versione), TRUE);
  versione_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (versione_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (versione), versione_icon_pixbuf);
      gdk_pixbuf_unref (versione_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (versione), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox5 = GTK_DIALOG (versione)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox3, TRUE, TRUE, 0);

  label9 = gtk_label_new (_("ComLinux\n(c)2004-2006 Giancarlo Capella\n"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox3), label9, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_CENTER);

  label_versione = gtk_label_new ("");
  gtk_widget_show (label_versione);
  gtk_box_pack_start (GTK_BOX (vbox3), label_versione, FALSE, FALSE, 0);

  dialog_action_area5 = GTK_DIALOG (versione)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (versione), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) versione, "realize",
                    G_CALLBACK (on_versione_realize),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (versione, versione, "versione");
  GLADE_HOOKUP_OBJECT_NO_REF (versione, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (versione, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (versione, label9, "label9");
  GLADE_HOOKUP_OBJECT (versione, label_versione, "label_versione");
  GLADE_HOOKUP_OBJECT_NO_REF (versione, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (versione, closebutton1, "closebutton1");

  return versione;
}

GtkWidget*
create_dialog_att (void)
{
  GtkWidget *dialog_att;
  GdkPixbuf *dialog_att_icon_pixbuf;
  GtkWidget *dialog_vbox6;
  GtkWidget *entry4;
  GtkWidget *dialog_action_area6;
  GtkWidget *cancelbutton4;
  GtkWidget *okbutton4;

  dialog_att = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_att), _("Attuatore"));
  gtk_window_set_modal (GTK_WINDOW (dialog_att), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_att), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_att), TRUE);
  dialog_att_icon_pixbuf = create_pixbuf ("wmaker-mech.tif");
  if (dialog_att_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_att), dialog_att_icon_pixbuf);
      gdk_pixbuf_unref (dialog_att_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog_att), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_att), FALSE);

  dialog_vbox6 = GTK_DIALOG (dialog_att)->vbox;
  gtk_widget_show (dialog_vbox6);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), entry4, FALSE, FALSE, 0);

  dialog_action_area6 = GTK_DIALOG (dialog_att)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  cancelbutton4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_att), cancelbutton4, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton4, GTK_CAN_DEFAULT);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_att), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_att, dialog_att, "dialog_att");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_att, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (dialog_att, entry4, "entry4");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_att, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (dialog_att, cancelbutton4, "cancelbutton4");
  GLADE_HOOKUP_OBJECT (dialog_att, okbutton4, "okbutton4");

  return dialog_att;
}

GtkWidget*
create_dialog_evento (void)
{
  GtkWidget *dialog_evento;
  GtkWidget *dialog_vbox7;
  GtkWidget *hbox3;
  GtkWidget *label12;
  GtkWidget *entry5;
  GtkWidget *label13;
  GtkWidget *entry6;
  GtkWidget *dialog_action_area7;
  GtkWidget *cancelbutton5;
  GtkWidget *okbutton5;

  dialog_evento = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_evento), _("Evento"));
  gtk_window_set_modal (GTK_WINDOW (dialog_evento), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog_evento), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox7 = GTK_DIALOG (dialog_evento)->vbox;
  gtk_widget_show (dialog_vbox7);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), hbox3, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Num:"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 2);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_box_pack_start (GTK_BOX (hbox3), entry5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry5, 20, -1);

  label13 = gtk_label_new (_("Evento:"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 2);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_box_pack_start (GTK_BOX (hbox3), entry6, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry6, 100, -1);

  dialog_action_area7 = GTK_DIALOG (dialog_evento)->action_area;
  gtk_widget_show (dialog_action_area7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area7), GTK_BUTTONBOX_END);

  cancelbutton5 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton5);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_evento), cancelbutton5, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton5, GTK_CAN_DEFAULT);

  okbutton5 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton5);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_evento), okbutton5, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton5, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_evento, dialog_evento, "dialog_evento");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_evento, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (dialog_evento, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dialog_evento, label12, "label12");
  GLADE_HOOKUP_OBJECT (dialog_evento, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (dialog_evento, label13, "label13");
  GLADE_HOOKUP_OBJECT (dialog_evento, entry6, "entry6");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_evento, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (dialog_evento, cancelbutton5, "cancelbutton5");
  GLADE_HOOKUP_OBJECT (dialog_evento, okbutton5, "okbutton5");

  return dialog_evento;
}

GtkWidget*
create_dialog_segreto (void)
{
  GtkWidget *dialog_segreto;
  GtkWidget *vbox4;
  GtkWidget *hbox4;
  GtkWidget *label14;
  GtkWidget *entry7;
  GtkWidget *label15;
  GtkWidget *entry8;
  GtkWidget *hbuttonbox1;
  GtkWidget *button2;
  GtkWidget *button3;

  dialog_segreto = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_segreto), _("Segreto"));
  gtk_window_set_modal (GTK_WINDOW (dialog_segreto), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog_segreto), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox4 = GTK_DIALOG (dialog_segreto)->vbox;
  gtk_widget_show (vbox4);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox4, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Num:"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 2);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_box_pack_start (GTK_BOX (hbox4), entry7, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry7, 20, -1);

  label15 = gtk_label_new (_("Segreto:"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 2);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_box_pack_start (GTK_BOX (hbox4), entry8, TRUE, TRUE, 0);
  gtk_widget_set_size_request (entry8, 100, -1);

  hbuttonbox1 = GTK_DIALOG (dialog_segreto)->action_area;
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_segreto), button2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_segreto), button3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_segreto, dialog_segreto, "dialog_segreto");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_segreto, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog_segreto, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (dialog_segreto, label14, "label14");
  GLADE_HOOKUP_OBJECT (dialog_segreto, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (dialog_segreto, label15, "label15");
  GLADE_HOOKUP_OBJECT (dialog_segreto, entry8, "entry8");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_segreto, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (dialog_segreto, button2, "button2");
  GLADE_HOOKUP_OBJECT (dialog_segreto, button3, "button3");

  return dialog_segreto;
}

GtkWidget*
create_dialog_generico (void)
{
  GtkWidget *dialog_generico;
  GtkWidget *dialog_vbox8;
  GtkWidget *entry9;
  GtkWidget *label16;
  GtkWidget *dialog_action_area8;
  GtkWidget *cancelbutton6;
  GtkWidget *okbutton6;

  dialog_generico = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog_generico, 300, -1);
  gtk_window_set_title (GTK_WINDOW (dialog_generico), _("Generico"));
  gtk_window_set_modal (GTK_WINDOW (dialog_generico), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog_generico), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox8 = GTK_DIALOG (dialog_generico)->vbox;
  gtk_widget_show (dialog_vbox8);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), entry9, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Per l'inserimento di valori binari\nutilizzare il prefisso # seguito dal\nvalore esadecimale del byte."));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), label16, FALSE, FALSE, 0);

  dialog_action_area8 = GTK_DIALOG (dialog_generico)->action_area;
  gtk_widget_show (dialog_action_area8);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area8), GTK_BUTTONBOX_END);

  cancelbutton6 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton6);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_generico), cancelbutton6, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton6, GTK_CAN_DEFAULT);

  okbutton6 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton6);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_generico), okbutton6, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton6, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_generico, dialog_generico, "dialog_generico");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_generico, dialog_vbox8, "dialog_vbox8");
  GLADE_HOOKUP_OBJECT (dialog_generico, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (dialog_generico, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_generico, dialog_action_area8, "dialog_action_area8");
  GLADE_HOOKUP_OBJECT (dialog_generico, cancelbutton6, "cancelbutton6");
  GLADE_HOOKUP_OBJECT (dialog_generico, okbutton6, "okbutton6");

  return dialog_generico;
}

